### ISSUE TITLE
It does not run automatically

### ISSUE THREAD

**Issue by andersonmoura** [NiJoao/LegendasTV-Downloader#10]
Hello.
I'm using Ubuntu 16.04 and Gnome 3.2
The script does not run automatically after start it in the terminal. It waits me to press any key to start running.
I've comment the line 141 -> getch = sys.stdin.read(1) to make it stop wait for me to press any key.

**Comment by NiJoao** [comment]
andersonmoura: The script accepted the "-s" argument to make it "silent".
I've improved that functionality and added it to the readme.
Please confirm.
