### ISSUE TITLE
Problema na descompressão.

### ISSUE THREAD

**Issue by thituto** [NiJoao/LegendasTV-Downloader#11]
Olá, primeiramente gostaria de parabenizar pelo excelente trabalho que fez. Buscava algo pra automatizar a busca de legendas e com este script resolveu basicamente todos meus problemas.

Estava tudo 100 % até a as séries que eu faço o download começou a dar erro de descompressão.
Como não sei a linguagem Python não consegui identificar sozinho o problema.  O que notei de diferente é que os arquivos .rar estão vindo com uma pasta dentro. Não sei se isto ocasiona o erro.

Conseguiria me ajudar a entender?

Exemplo de mensagem:
Extracted Supernatural.S12E13.1080p.HDTV.X264-DIMENSION.srt with 100%
Extracting subtitle as: Supernatural.S12E13.1080p.HDTV.X264-DIMENSION[rarbg].srt
! Error, decrompressing!

Obrigado.

**Comment by NiJoao** [comment]
Fixed in new version. Please test.
