### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by andersonmoura** [NiJoao/LegendasTV-Downloader#5]
Hi there...
I have used this script for a while and suddenly i started recieve this error:

PS D:\Vídeos> .\ltv-downloader.py "G:\Grey's Anatomy\Greys.Anatomy.S11E08.720p.HDTV.X264-DIMENSION.mkv"
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 129, in "module"
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax

-------
I have reinstalled python (Using 3.4.3) and the modules beautifulsoup4 rarfile using Windows

**Comment by NiJoao** [comment]
Hey Anderson,
Nice to hear someone is using it! :)

I just updated the script with lots of improvements and fixes.
Can you please check if that error still occurs with the latest version?

Regards

**Comment by andersonmoura** [comment]
Are you kidding? People who doesn't use this script, doesn't know it exists... Thanks a alot for it. Its amazing.

So, after update the script with the new version, i'm having another problem... Now its trying to install the libraries.

I already have the libraries installed.
Even using --upgrade won't work.
I'm running using an administrator prompt 

>
PS D:\Vídeos> .\ltv-downloader.py "D:\Vídeos\Séries\The Walking Dead\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-
KILLERS[brassetv]\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILLERS.mkv"
Installing requirements: ['requests', 'beautifulsoup4', 'rarfile']
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rarfile in c:\python34\lib\site-packages

Python modules needed: beautifulsoup4, rarfile, requests
We failled to install them automatically.

Try running this with Admin Priviliges, or
Run in a command prompt Admin Priviliges:

pip install requests beautifulsoup4 rarfile

Press any key to exit...

**Comment by NiJoao** [comment]
Hi, thanks!
Somehow, the libraries fail to load in your installation.
I improved the debug of the script, can you run the new version and paste the result here?

**Comment by andersonmoura** [comment]
Hi!!!
>
PS D:\Vídeos> .\ltv-downloader.py "D:\Vídeos\Séries\The Walking Dead\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-
KILLERS[brassetv]\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILLERS.mkv"
! Missing requirements. <class 'SyntaxError'>
Installing: ['requests', 'beautifulsoup4', 'rarfile']
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rarfile in c:\python34\lib\site-packages
>
Python modules needed: beautifulsoup4, rarfile, requests
We failled to install them automatically: <class 'SyntaxError'>
>
Try running this with Admin Priviliges, or
Run in a command prompt Admin Priviliges:
>
pip install requests beautifulsoup4 rarfile
>
Press any key to exit...

Before i make you waste more time in a problem that seems i'm the only one having, i'll try on another pc. On this pc i'm testing the win 10 preview and maybe that is the problem.

**Comment by NiJoao** [comment]
That might be the problem, but it shouldn't happen either way.
I Included even more debug info in a new version now available.
Can you try again?

And also, can you open an admin terminal (cmd or powershell), and type:

python

and then:
import requests
from bs4 import BeautifulSoup
from rarfile import RarFile

And paste here the results.
Thanks

**Comment by andersonmoura** [comment]
No problem... If you don't mind, i'm glad to provide the info you need.

Here is the result of running the script:
>
PS D:\> cd .\Vídeos
PS D:\Vídeos> .\ltv-downloader.py "D:\Vídeos\Séries\The Walking Dead\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-
KILLERS[brassetv]\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILLERS.mkv""D:\Vídeos\Séries\The Walking Dead\The.
Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILLERS[brassetv]\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILL
ERS.mkv"
! Missing requirements. class 'SyntaxError'
Installing: ['requests', 'beautifulsoup4', 'rarfile']
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rarfile in c:\python34\lib\site-packages
>
Python modules needed: beautifulsoup4, rarfile, requests
We failled to install them automatically: class 'SyntaxError'
! Traceback:
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 114, in module
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>
During handling of the above exception, another exception occurred:
>
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 136, in module
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>
>
Try running this with Admin Priviliges, or
Run in a command prompt Admin Priviliges:
>
pip install requests beautifulsoup4 rarfile
>
Press any key to exit...

Here running the commands:

>
PS D:\Vídeos> python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> from bs4 import BeautifulSoup
Traceback (most recent call last):
  File "<stdin>", line 1, in module
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>>> from rarfile import RarFile
>>>
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 1862, in shutdown
    def shutdown(handlerList=_handlerList):
KeyboardInterrupt
PS D:\Vídeos>

On the import for RarFile, it didn't gave me any result... I had to cancel (Ctrl+C) to finish. It spend like 10 min, without response before i cancel

**Comment by NiJoao** [comment]
I think you have installed beautifulsoup4 for python 2.x instead of 3.x
Open an admin terminal and do these:
python -V
pip install --upgrade --force-reinstall beautifulsoup4

**Comment by andersonmoura** [comment]
>
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. Todos os direitos reservados.
>
PS C:\WINDOWS\system32> python -V
Python 3.4.3
PS C:\WINDOWS\system32> pip install --upgrade --force-reinstall beautifulsoup4
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
    100% |################################| 143kB 544kB/s
Installing collected packages: beautifulsoup4
  Found existing installation: beautifulsoup4 4.3.2
    Uninstalling beautifulsoup4-4.3.2:
      Successfully uninstalled beautifulsoup4-4.3.2
  Running setup.py install for beautifulsoup4
Successfully installed beautifulsoup4-4.3.2
PS C:\WINDOWS\system32> d:
PS D:\> cd .\Vídeos
PS D:\Vídeos> .\ltv-downloader.py "D:\Vídeos\Séries\The Walking Dead\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-
KILLERS[brassetv]\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILLERS.mkv"
! Missing requirements. class 'SyntaxError'
Installing: ['requests', 'beautifulsoup4', 'rarfile']
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rarfile in c:\python34\lib\site-packages
>
Python modules needed: beautifulsoup4, rarfile, requests
We failled to install them automatically: class 'SyntaxError'
! Traceback:
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 114, in module
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>
During handling of the above exception, another exception occurred:
>
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 136, in module
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>
>
Try running this with Admin Priviliges, or
Run in a command prompt Admin Priviliges:
>
pip install requests beautifulsoup4 rarfile
>
Press any key to exit...

**Comment by NiJoao** [comment]
Hmm, it seams you'r PIP is not converting the BS4 package to python 3 during setup.
Try to do it manually like this:

cd C:\Python34\Lib\site-packages
python C:\Python34\Tools\Scripts\2to3.py -w bs4

**Comment by NiJoao** [comment]
If it still doesn't work, try installing bs4 from source like this:

In Admin PowerShell:
pip uninstall beautifulsoup4

Download and extract this: http://www.crummy.com/software/BeautifulSoup/bs4/download/4.3/beautifulsoup4-4.3.2.tar.gz

In Admin PowerShell:
cd C:\beautifulsoup4-4.3.2   (or whatever)
python C:\Python34\Tools\Scripts\2to3.py -w bs4
python setup.py install

**Comment by NiJoao** [comment]
BTW, what's the output of:
pip -V
?

If it doesn't end in "(python 3.4)", you have multiple pythons installed and are running the wrong pip-version.
There are some workarounds (like installing from source, see previous source), but future problems will arise.
If you don't need version 2.x, my advise is to uninstall every python version you have, deleting their references from the PATH variable and the C:/Python* folders, and then installing Python 3.4.

**Comment by andersonmoura** [comment]
At work now... I'll do all you suggest as soon as possible and let you now the result.... Thanks for now.

**Comment by andersonmoura** [comment]
PIP Version
>
PS C:\WINDOWS\system32> pip -V
pip 6.0.8 from C:\Python34\lib\site-packages (python 3.4)

Converting Packages (Lots of code and then in the end...)
>
WARNING: couldn't encode .\bs4\tests\test_tree.py's diff for your terminal
RefactoringTool: Files that were modified:
RefactoringTool: .\bs4\__init__.py
RefactoringTool: .\bs4\dammit.py
RefactoringTool: .\bs4\diagnose.py
RefactoringTool: .\bs4\element.py
RefactoringTool: .\bs4\testing.py
RefactoringTool: .\bs4\builder\__init__.py
RefactoringTool: .\bs4\builder\_html5lib.py
RefactoringTool: .\bs4\builder\_htmlparser.py
RefactoringTool: .\bs4\builder\_lxml.py
RefactoringTool: .\bs4\tests\__init__.py
RefactoringTool: .\bs4\tests\test_builder_registry.py
RefactoringTool: .\bs4\tests\test_docs.py
RefactoringTool: .\bs4\tests\test_html5lib.py
RefactoringTool: .\bs4\tests\test_htmlparser.py
RefactoringTool: .\bs4\tests\test_lxml.py
RefactoringTool: .\bs4\tests\test_soup.py
RefactoringTool: .\bs4\tests\test_tree.py

I got the same erros running the script...

Removing the library

>
PS D:\Vídeos> pip uninstall beautifulsoup4
DEPRECATION: Uninstalling a distutils installed project (beautifulsoup4) has been deprecated and will be removed in a fu
ture version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
Uninstalling beautifulsoup4-4.3.2:
  c:\python34\lib\site-packages\beautifulsoup4-4.3.2-py3.4.egg-info
Proceed (y/n)? y
  Successfully uninstalled beautifulsoup4-4.3.2
PS D:\Vídeos>

Converting again and re-installing

>
RefactoringTool: No changes to bs4\tests\test_tree.py
RefactoringTool: Files that were modified:
RefactoringTool: bs4\__init__.py
RefactoringTool: bs4\dammit.py
RefactoringTool: bs4\diagnose.py
RefactoringTool: bs4\element.py
RefactoringTool: bs4\testing.py
RefactoringTool: bs4\builder\__init__.py
RefactoringTool: bs4\builder\_html5lib.py
RefactoringTool: bs4\builder\_htmlparser.py
RefactoringTool: bs4\builder\_lxml.py
RefactoringTool: bs4\tests\__init__.py
RefactoringTool: bs4\tests\test_builder_registry.py
RefactoringTool: bs4\tests\test_docs.py
RefactoringTool: bs4\tests\test_html5lib.py
RefactoringTool: bs4\tests\test_htmlparser.py
RefactoringTool: bs4\tests\test_lxml.py
RefactoringTool: bs4\tests\test_soup.py
RefactoringTool: bs4\tests\test_tree.py

Re-installing
>
PS D:\Downloads\beautifulsoup4-4.3.2> python setup.py install
running install
running build
running build_py
copying bs4\diagnose.py -> build\lib\bs4
copying bs4\element.py -> build\lib\bs4
copying bs4\__init__.py -> build\lib\bs4
copying bs4\tests\test_soup.py -> build\lib\bs4\tests
Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
running install_lib
copying build\lib\bs4\diagnose.py -> C:\Python34\Lib\site-packages\bs4
copying build\lib\bs4\element.py -> C:\Python34\Lib\site-packages\bs4
copying build\lib\bs4\tests\test_soup.py -> C:\Python34\Lib\site-packages\bs4\tests
copying build\lib\bs4\__init__.py -> C:\Python34\Lib\site-packages\bs4
byte-compiling C:\Python34\Lib\site-packages\bs4\diagnose.py to diagnose.cpython-34.pyc
byte-compiling C:\Python34\Lib\site-packages\bs4\element.py to element.cpython-34.pyc
byte-compiling C:\Python34\Lib\site-packages\bs4\tests\test_soup.py to test_soup.cpython-34.pyc
byte-compiling C:\Python34\Lib\site-packages\bs4\__init__.py to __init__.cpython-34.pyc
running install_egg_info
Writing C:\Python34\Lib\site-packages\beautifulsoup4-4.3.2-py3.4.egg-info

Running the script
>
PS D:\Vídeos> .\ltv-downloader.py "D:\Vídeos\Séries\The Walking Dead\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-
KILLERS[brassetv]\The.Walking.Dead.S05E16.REAL.PROPER.720p.HDTV.x264-KILLERS.mkv"
! Missing requirements. class 'SyntaxError'
Installing: ['requests', 'beautifulsoup4', 'rarfile']
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rarfile in c:\python34\lib\site-packages
>
Python modules needed: beautifulsoup4, rarfile, requests
We failled to install them automatically: class 'SyntaxError'
! Traceback:
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 114, in module
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>
During handling of the above exception, another exception occurred:
>
Traceback (most recent call last):
  File "D:\Vídeos\ltv-downloader.py", line 136, in module
    from bs4 import BeautifulSoup
  File "C:\Python34\lib\bs4\__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
>
>
Try running this with Admin Priviliges, or
Run in a command prompt Admin Priviliges:
>
pip install requests beautifulsoup4 rarfile
>
Press any key to exit...

I guess i should try remove everything and reinstall from zero...

**Comment by andersonmoura** [comment]
After reinstall everything, it worked again they way it should... It made the download e install of the libraries and then the download of the subtitle...

Thanks a lot for the help man e of course for this amazing script

**Comment by NiJoao** [comment]
Good to know it's working!
Was starting to get scared of upgrading to Windows 10...
Regards
