### ISSUE TITLE
Error with TV Shows folders

### ISSUE THREAD

**Issue by rotavio** [NiJoao/LegendasTV-Downloader#6]
My folder structure is created by SickBeard and is as follow:
     d:\TV\Show Name\Season 01\file.name.mkv

Some Shows have the Year appended to the folder name, which is causing an error when running the script:

    Recursing directory: D:\TV\watch\ShowName (2010)
    Searching for: http://www.omdbapi.com/?y=2010&t=ShowName
    Traceback (most recent call last):
      File "E:\Software\LegendasTV-Downloader-master\ltv-downloader.py", line 1482,
    in <module>
        originalFilename = getAppendRating((os.path.abspath(originalFilename)))
      File "E:\Software\LegendasTV-Downloader-master\ltv-downloader.py", line 1015,
    in getAppendRating
        print('Got imdb: '+str(data))
      File "C:\Python34\lib\encodings\cp850.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_map)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position
    605: character maps to <undefined>

**Comment by NiJoao** [comment]
Hi,
The problem, I think, is caused by a non-standard character (EN DASH) in the episode/show name, which is not compatible with your terminal/window.
Anyway, I added a function forcing ASCII encoding in the OMDBAPI results, it should work now.
Regards

**Comment by rotavio** [comment]
It worked! Thanks!
